language: cpp

ruby: jruby

compiler:
 - gcc
 - clang

before_script:
 - rvm install jruby
 - bundle install
 - sudo apt-get install libquickfix-dev
 - ./autogen.sh

script: ./configure && make && bundle exec cucumber
