language: cpp

ruby: jruby

compiler:
 - gcc

before_script:
 - rvm install jruby
 - rvm use jruby && bundle install
 - sudo apt-get install libquickfix-dev
 - ./autogen.sh

script: ./configure && make && rvm use jruby && bundle exec cucumber
